---
- name: Ensure auditd functions
  hosts: "{{ target_host }}"
  become: yes
  become_method: enable
  tasks:
  - name: Ensure audit is installed
    ansible.builtin.dnf:
      name: audit
      state: present
    when: molecule_testing is not defined

  - name: Ensure auditd rule file is according to Security baseline
    ansible.builtin.copy:
      src: audit.rules
      dest: /etc/audit/rules.d/audit.rules
      owner: root
      group: root
      mode: 0600
    when: molecule_testing is not defined

  - name: Ensure auditd daemon is started and enabled
    ansible.builtin.service:
      name: auditd
      state: started
      enabled: true
    when: molecule_testing is not defined
