---
- name: Ensure hosts file is properly configured
  hosts: "{{ target_host }}"
  become: yes
  become_method: enable
  tasks:
  - name: Ensure template for /etc/hosts
    ansible.builtin.template:
      src: templates/hosts.j2
      dest: /etc/hosts
      owner: root
      group: root
      mode: 0644
