---
- name: Ensure RPM baseline is in place
  hosts: "{{ target_host }}"
  become: yes
  become_method: enable
  tasks:
  - name: Ensure RPMs that are included in the Security baseline are installed
    ansible.builtin.dnf:
      name:
        - audit
        - rsyslog
        - aide
        - firewalld
        - lsof
        - wget
      state: present
