---
- name: Ensure auditd functions
  hosts: "{{ target_host }}"
  become: yes
  become_method: enable
  tasks:
  - name: Ensure /etc/sysctl.conf configuration is correct
    ansible.builtin.copy:
      src: sysctl.conf
      dest: /etc/sysctl.conf
      mode: '0644'
      owner: 'root'
      group: 'root'

  - name: Ensure /etc/sysctl.d exists
    ansible.builtin.file:
      path: /etc/sysctl.d
      state: directory
      owner: 'root'
      group: 'root'
      mode: '0755'

  - name: Ensure /etc/sysctl.d/zbaseline.conf configuration is correct
    ansible.builtin.copy:
      src: zbaseline.conf
      dest: /etc/sysctl.d/zbaseline.conf
      mode: '0644'
      owner: 'root'
      group: 'root'

  - name: Set sysctl parameters
    ansible.posix.sysctl:
      name: net.ipv4.tcp_syncookies
      value: 1
      state: present
      reload: true
      sysctl_set: true
 
